#!/bin/bash
##########################################################################
##
## dd_write
## 
##  This file reads and writes data to/from disk...
##########################################################################
DD=/bin/dd
BS=256k
COUNT=300
TMPDIR=/tmp/ddout/
mkdir -p ${TMPDIR}
i=1
# while true
# do
	FILE=${TMPDIR}file.${i}
	echo ---- $i read/write file ${FILE} ----
	$DD if=/dev/urandom of=${FILE} bs=${BS} count=${COUNT} conv=fdatasync
	$DD if=${FILE} of=/dev/null bs=${BS} count=${COUNT} 
	rm ${FILE} 
	let i=i+1
#sleep 1
# done
echo "DD Test complete!"

