#!/bin/bash
##########################################################################
##
## dd_write
## 
##  This file reads and writes data to/from disk...
##########################################################################
DD=/bin/dd
BS=256k
COUNT=3000
TMPDIR=/tmp/ddout/
mkdir -p ${TMPDIR}
i=1
while true
do
	FILE=${TMPDIR}${i}
	echo ---- $i read/write file ${FILE} ----
	$DD if=/dev/zero of=${FILE} bs=${BS} count=${COUNT}
	$DD if=${FILE} of=/dev/zero bs=${BS} count=${COUNT}
	rm ${TMPDIR}${i} 
	let i=i+1
	sleep 1
done

